### ISSUE TITLE
Support for Android?

### ISSUE THREAD

**Issue by elliotstokes** [Calq/Client-Cordova#1]
Is there any technical reasons why there is currently no Android Support?

Do you have any plans to add? If i were to implement myself are there any possible roadblocks?

**Comment by RRAway** [comment]
No technical reason. The Cordova plugin was made ad-hoc for a specific client that only warranted iOS support at the time.

It should be relatively straightforward to add Android support. The plugin just needs to wrap our (existing) native Android SDK in the same way it does our native iOS SDK. Both native libraries have feature parity and almost identical methods so there shouldn't be any major hurdles if you wanted to give it a go (though I should caveat that by saying we are by no means Cordova experts in house - we just occasionally moonlight).

**Comment by elliotstokes** [comment]
Thanks for getting back. Were currently looking at various Analytics packages and may come back to this.
